### ISSUE TITLE
Git Meetup v0.1.0 - 8th April 2015

### ISSUE THREAD

**Issue by Valentine** [GrumpyGits/grumpygits.sg#4]
It's Git's 10th anniversary, and we're having our first ever Git user meetup in Singapore! 

This meetup is aimed at both beginners and people who have over 10 years of Git experience (wait a minute…). We hope to stretch your Gitability level, and better your understanding of version control systems!

**Date:** Wednesday, 8 April 2015, 7:30 PM
**Location:** ThoughtWorks, [87B Amoy Street, 3rd Floor, Singapore 069906](https://www.google.com.sg/maps/place/87+Amoy+St,+Singapore+069906/@1.280945,103.847069,17z/data=!4m2!3m1!1s0x31da190d0d40faef:0x44ff97a7c1dae89b)

[![](https://cloud.githubusercontent.com/assets/676061/7008435/28197214-dcc5-11e4-968e-f1578a120dd2.png)](https://www.google.com.sg/maps/place/87+Amoy+St,+Singapore+069906/@1.2828864,103.8457601,17z/data=!4m2!3m1!1s0x31da190d0d40faef:0x44ff97a7c1dae89b)

## Programme

* "A brief history of Git": Sahil Bajaj (@spinningarrow)
* "Git for Teams": Sayanee Basu (@sayanee)
* "Git Internals": Chow Loong Jin (@hyperair)
* Five random Git tips: ChernJie (@chernjie)

Come merge with your fellow Gits!

Interested in speaking? Please talk to @Valentine or @chernjie! (We're looking for lightning talks!)

**Venue and food sponsor:** [ThoughtWorks](http://www.thoughtworks.com/) (thanks guys!)

For future events, please join our [Facebook](https://www.facebook.com/groups/sggrumpygits/) and [Meetup](http://www.meetup.com/Grumpy-Gits-SG/) groups.

**RSVP** on [Facebook](https://www.facebook.com/events/1599023443666373/), [Meetup](http://www.meetup.com/Grumpy-Gits-SG/events/221519416/), or by :+1:-ing this issue!

**Comment by Valentine** [comment]
Inviting @KopiJS folks: @cheeaun @chuyeow @notthetup @ctrlaltreboot @fadhlirahim @burnflare @jpibarra1130 @kaihendry @teohm @ctrlaltreboot @dqminh @miccheng @AudreyLim @stuti90 @yeouchien @jacki3lene @cbas @alyssaq @choonkeat @creativepsyco @ngourlay @mfirdaus @zz85 @miccheng @liuziyi @chenzihui @meiwin @gigablah @angelorohit @yohanesyuen @ardydedase @ahkeno @soareschen @renettarenula @dqminh @viettienn @honcheng @tensaix2j @phungleson @liangzan @zhenyi @winston @yongfook @kahwee @chikathreesix @shiawuen @stephanfeb @yohanesyuen @robertsky @d10 @shortdiv @duykhoa and everyone else!

**Comment by miccheng** [comment]
Sorry, realize it's my colleague's farewell dinner tonight. Have to give it
a miss.

**Comment by winston** [comment]
I typically can't do Wednesdays. :disappointed:

**Comment by choonkeat** [comment]
Luckily it's tonight, Tuesday @winston 👻

**Comment by choonkeat** [comment]
`Wednesday, 7 April 2015, 7:30 PM`  Lol need rebase

**Comment by winston** [comment]
@choonkeat I think they got the date wrong.. https://www.facebook.com/events/1599023443666373/
@Valentine 7 or 8 apr???

**Comment by choonkeat** [comment]
First meetup has conflict. So git

**Comment by winston** [comment]
> So git
lol!

**Comment by kahwee** [comment]
So not on Apr 8 any more. I can't make it today. :(

But please have fun!

**Comment by ahkeno** [comment]
if it is today ,can't make it ! Conflict with book club 
http://www.meetup.com/Singapore-JS/events/221393166/

**Comment by spinningarrow** [comment]
Sorry for the confusion people! The meetup is **tomorrow**, i.e. on 8 April 2015.

**Comment by miccheng** [comment]
Clashes with WebRTC meetup.

http://www.meetup.com/Singapore-WebRTC-Meetup/events/221569159/

**Comment by zz85** [comment]
Facebook event says Wednesday? @valentine @chernjie would be nice if you could update this issue's subject to avoid confusion...

**Comment by creativepsyco** [comment]
Sorry I shall be at the hackware event.
https://www.facebook.com/events/1588901321352055/

On Tue, Apr 7, 2015 at 12:23 PM, Joshua Koo <notifications@github.com>
wrote:

> Facebook event says Wednesday? @valentine <https://github.com/valentine>
> @chernjie <https://github.com/chernjie> would be nice if you could update
> this issue's subject to avoid confusion...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GrumpyGits/grumpygits.sg/issues/4#issuecomment-90354317>
> .
>



-- 
Mohit Singh KANWAL (Mr)

[image: Facebook] <http://facebook.com/mohitkanwal>  [image: Twitter]
<http://twitter.com/mohitkanwal>

**Comment by notthetup** [comment]
:+1:  For Hackware! :stuck_out_tongue:

**Comment by Valentine** [comment]
Oh no it seems my brain wasn't working when I posted this up! Yes, it's tomorrow.

Thanks @choonkeat @winston @kahwee @ahkeno @miccheng @zz85 for bringing this up. So paiseh urgh.

Sorry guys!

(@creativepsyco See you next time!)

**Comment by d10** [comment]
Sorry can't make it :(

**Comment by chernjie** [comment]
This issue was moved to GrumpyGits/grumpygits.github.io#2
